
# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

readme = ''

setup(
    long_description=readme,
    name='django_contrib_admin_react',
    version='0.1.1',
    description='Creates viewsets and serializers for models in your admin site to use with react-admin',
    python_requires='==3.*,>=3.8.0',
    project_urls={
        "homepage": "https://github.com/khchine5/django_contrib_admin_react"},
    author='ph',
    author_email='robotnaoborot@gmail.com',
    packages=['django_contrib_admin_react', 'django_contrib_admin_react.management',
              'django_contrib_admin_react.management.commands', 'django_contrib_admin_react.migrations', 'django_contrib_admin_react.static'],
    package_dir={"": "."},
    package_data={"django_contrib_admin_react": ["src/*.js", "src/*.json", "src/*.lock", "src/*.md", "src/public/*.html", "src/public/*.ico", "src/public/*.json",
                                         "src/public/*.png", "src/public/*.txt", "src/src/*.css", "src/src/*.js", "src/src/*.svg", "templates/django_contrib_admin_react/*.html"]},
    install_requires=['django==3.*,>=3.0.0',
                      'django-filter==2.*,>=2.2.0', 'djangorestframework==3.*,>=3.10.0'],
    extras_require={"dev": ["pytest==3.*,>=3.0.0"]},
)
